name:               "Unhandled Exception"
description:        "everyday a developer wakes up and starts coding"

#url:                "blog.unhandledexception.it"
#author:             "nezumi"
gravatar_hash:      "082fcf499b13603f2d604b0afaf7f89d"
twitter:            "emagar83"
github:             "nezumi-quasar"
linkedin:           "emanuele-garofalo-ba12ab31"

linkedin_url:       "http://bit.ly/2e8dXx8"
disqus_shortname:   "thinker3197"

background:         "/assets/imgs/deserve_bg.jpg"
resources:          "resources"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Slideshares"
    href:           "/pages/slideshares"
  - name:           "Bio"
    href:           "/pages/bio"
  - name:           "Publications"
    href:           "/pages/publications"

sass:
  sass_dir: resources/css
  style:    expanded

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
